project:
  type: website
  render:
    - "*.qmd"

website:
  title: "Numberbank"
  navbar:
    left:
      - text: Data
        href: data.qmd
      - methods.qmd
      - contributors.qmd
      - submit.qmd
    tools:
      - icon: github
        href: https://github.com/langcog/numberbank

format:
  html:
    theme: [cosmo, scss/global.scss]

execute: 
  echo: false
  message: false
  warning: false
  error: false
